

from rest_framework.routers import DefaultRouter
from .views import MemoryViewSet

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView 

router = DefaultRouter()
router.register(r'memories', MemoryViewSet, basename='memory')

# The urlpatterns are generated by the router
urlpatterns = router.urls